version: '3'

volumes:
  db:


services:
  app:
    container_name: kaizoku
    build: 
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-kaizoku}:${DATABASE_PASSWORD:-kaizoku}@db:${DATABASE_PORT:-5432}/${DATABASE_SCHEMA:-kaizoku}
      - REDIS_HOST=redis
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    env_file:
      - .env
    volumes:
      - ./kaizoku/data:/data
      - ./kaizoku/config:/config
      - ./kaizoku/logs:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${KAIZOKU_PORT:-3000}:3000"
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kaizoku" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER:-kaizoku}
      - POSTGRES_DB=${DATABASE_SCHEMA:-kaizoku}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-kaizoku}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"
  apprise:
    image: caronc/apprise:latest
    ports:
      - "9292:8000"