version: '3'

volumes:
  db:


services:
  app:
    container_name: kaizoku
    build: .
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_SCHEMA}
      REDIS_HOST: redis
    env_file:
      - .env
    volumes:
      - /home/alperen/Manga:/data/manga
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:3000"
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kaizoku" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
