version: '3'

volumes:
  db:


services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kaizoku" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
