name: Feature request
description: Suggest an idea for this project
labels: [ "feature" ]
body:
  - type: textarea
    attributes:
      label: Feature Description
      placeholder: "I'm always frustrated when ..."
      description: "A clear and concise description of what the problem is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution you would like
      description: "A clear and concise description of how you want it to be implemented."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives you have considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Thank you for making Kaizoku better! ✨**